# Don't print a new line at the start of the prompt
add_newline = false
format = """
[╭─](#1E526A) [$directory](grey) $git_branch$git_commit$git_state$git_status
[╰─](#1E526A) [$username@$hostname](bright-grey) $character
"""

[character]
format = "[>](bold white) "

[username]
show_always = true
format = "$user"

#[directory]
#format = "$path"

[hostname]
ssh_only = false
format = "$hostname"

[git_status]
format = '([\[[$conflicted$stashed$deleted$renamed$modified](bold red)[$staged](green)[$untracked](grey)[$ahead_behind](cyan bold)\]]($style) )'
style = 'bold purple'

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

