# Don't print a new line at the start of the prompt
add_newline = false
format = '''
[╭─\(](#1E526A)[$directory](grey)[\)─╼](#1E526A) $git_branch$git_commit$git_state$git_status
[╰─╼](#1E526A) [$username@$hostname](bright-grey) $character
'''

[character]
format = "[❯](bold green) "

[directory]
truncate_to_repo = false
format = "$path"

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[[$conflicted$stashed$deleted$renamed$modified](bold red)[$staged](green)[$untracked](grey)[$ahead_behind](cyan bold)\]]($style) )'
style = 'bold purple'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
staged = '[++\($count\)](green)'
