theme = "my_theme"

[editor]
line-number = "relative"
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type", "separator", "spacer", "version-control", "spacer"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40
wrap-indicator = ""  # set wrap-indicator to "" to hide it


[keys.normal]
c = "move_char_left"
t = "move_line_down"
s = "move_line_up"
r = "move_char_right"
l = "change_selection"
C-v = "select_mode"
C-w = { c = "jump_view_left", t = "jump_view_down", s = "jump_view_up", r = "jump_view_right" }
C-s = "select_regex"
C-n = "goto_next_paragraph"
C-p = "goto_prev_paragraph"
T = "copy_selection_on_next_line"
S = "copy_selection_on_prev_line"
A-r = "replace"
A-s = "save_selection"
"backspace" = "goto_last_accessed_file"
"ret" = ":buffer-next"

[keys.insert]
C-c = "normal_mode"

[keys.select]
c = "extend_char_left"
t = "extend_line_down"
s = "extend_line_up"
r = "extend_char_right"
"C-s" = "select_regex"
l = "change_selection"
C-n = "goto_next_paragraph"
C-p = "goto_prev_paragraph"
A-r = "replace"
